![imagen](./img/ejercicios.png)

# INFORMACIÓN DEL PROYECTO

### TÍTULO

¿Dónde viven las mujeres más seguras? Un análisis global de seguridad femenina

### TEMA

El objetivo es identificar qué países ofrecen mejores condiciones de seguridad para las mujeres y qué factores explican estas diferencias. Este proyecto analiza la seguridad femenina a nivel global combinando indicadores de:
- percepción de seguridad (caminar sola de noche)
- seguridad en el hogar
- igualdad legal
- derechos de movilidad
- protección jurídica

### HIPÓTESIS

Define aquí lo que será la hipótesis de tu proyecto.
Deberás tener más de una, pero tu proyecto lo harás teniendo una principal hipótesis.

- Hipótesis 1:
Los países con mayor igualdad legal presentan mejores indicadores de seguridad femenina.
- Hipótesis 2:
La percepción de seguridad no siempre coincide con los datos reales de criminalidad o protección legal.
- Hipótesis 3:
Europa Occidental es la región donde las mujeres se sienten más seguras.
- Hipótesis 4:
España está mejor posicionada de lo que solemos pensar.

## OBTENCIÓN DE LOS DATOS

### DATASETS Y FUENTES ALTERNATIVAS DE DATOS

Incluye aquí una vista del dataset o datasets de los que partirás para poder evaluar tu hipótesis. <br>
También incluye el origen de estos datos y su fuente.

In [1]:
import pandas as pd
# guarda en variables los datasets y su fuente

fuente = "World Bank"

df_women_1 = pd.read_csv("data_women/WB_GS.csv") # Estadísticas de género, abarcan demografía, educación, salud, acceso a oportunidades económicas, vida pública, toma de decisiones, autonomía y capacidad de acción

df_women_2 = pd.read_csv("data_women/WB_WBL.csv") # Mujeres, empresa y la ley, Tema de Seguridad

df_women_3 = pd.read_csv("data_women/WEF_TTDI_SAFEWALK.csv") # Seguridad al caminar sola de noche

df_women_4 = pd.read_csv("data_women/WB_SSGD_PCT_POP_UNSAFE_HOME.csv") # Inseguridad frente al crimen en el hogar

df_women_5 = pd.read_csv("data_women/GI_AII_82.csv") # Derecho a viajar de forma independiente

Muestra mediante un head() los principales datasets con los que vas a trabajar

In [ ]:
df_women_1.head()

In [4]:
df_women_2.head()

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,...,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3_LABEL,AGG_METHOD_LABEL,UNIT_TYPE_LABEL,DECIMALS_LABEL,DATABASE_ID_LABEL,TIME_FORMAT_LABEL,UNIT_MULT_LABEL,OBS_STATUS_LABEL,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,SRB,GD_WBL_ENT,_Z,_Z,_Z,SCORE,...,Index component: Are there Government-Led Serv...,Not Applicable,Not Applicable,Number (real number),Two,"Women, Business and the Law (WBL)",CCYY,Units,Normal value,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,SRB,GD_WBL_ENT,_Z,_Z,_Z,SCORE,...,Total,Not Applicable,Not Applicable,Number (real number),Two,"Women, Business and the Law (WBL)",CCYY,Units,Normal value,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,SRB,GD_WBL_ENT,_Z,_Z,_Z,SCORE,...,"Index component: In Your Opinion, To What Exte...",Not Applicable,Not Applicable,Number (real number),Two,"Women, Business and the Law (WBL)",CCYY,Units,Normal value,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,SRB,GD_WBL_ENT,_Z,_Z,_Z,SCORE,...,"Index component: In Your Opinion, To What Exte...",Not Applicable,Not Applicable,Number (real number),Two,"Women, Business and the Law (WBL)",CCYY,Units,Normal value,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,SRB,GD_WBL_ENT,_Z,_Z,_Z,SCORE,...,"Index component: In Your Opinion, To What Exte...",Not Applicable,Not Applicable,Number (real number),Two,"Women, Business and the Law (WBL)",CCYY,Units,Normal value,Public

In [5]:
df_women_3.head()

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,...,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT,TIME_FORMAT_LABEL,COMMENT_OBS,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,ALB,Albania,WEF_TTDI_SAFEWALK,"Safety walking alone at night, 0-1 (best)",_T,...,Units,IX,Index,602,CCYY,NaN,A,Normal value,PU,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,ALB,Albania,WEF_TTDI_SAFEWALK,"Safety walking alone at night, 0-1 (best)",_T,...,Units,IX,Index,602,CCYY,NaN,A,Normal value,PU,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,ALB,Albania,WEF_TTDI_SAFEWALK,"Safety walking alone at night, 0-1 (best)",_T,...,Units,IX,Index,602,CCYY,NaN,A,Normal value,PU,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,ALB,Albania,WEF_TTDI_SAFEWALK,"Safety walking alone at night, 0-1 (best)",_T,...,Units,IX,Index,602,CCYY,NaN,A,Normal value,PU,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,ALB,Albania,WEF_TTDI_SAFEWALK,"Safety walking alone at night, 0-1 (best)",_T,...,Units,IX,Index,602,CCYY,NaN,A,Normal value,PU,Public

In [6]:
df_women_4.head()

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,...,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT,TIME_FORMAT_LABEL,COMMENT_OBS,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,_O,Other,AND,Andorra,WB_SSGD_PCT_POP_UNSAFE_HOME,Percentage of population who feel unsafe from ...,_T,...,Units,RATIO,Ratio,602,CCYY,NaN,A,Normal value,PU,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,_O,Other,AND,Andorra,WB_SSGD_PCT_POP_UNSAFE_HOME,Percentage of population who feel unsafe from ...,F,...,Units,RATIO,Ratio,602,CCYY,NaN,A,Normal value,PU,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,_O,Other,AND,Andorra,WB_SSGD_PCT_POP_UNSAFE_HOME,Percentage of population who feel unsafe from ...,_T,...,Units,RATIO,Ratio,602,CCYY,NaN,A,Normal value,PU,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,_O,Other,AND,Andorra,WB_SSGD_PCT_POP_UNSAFE_HOME,Percentage of population who feel unsafe from ...,_T,...,Units,RATIO,Ratio,602,CCYY,NaN,A,Normal value,PU,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,_O,Other,AND,Andorra,WB_SSGD_PCT_POP_UNSAFE_HOME,Percentage of population who feel unsafe from ...,_T,...,Units,RATIO,Ratio,602,CCYY,NaN,A,Normal value,PU,Public

In [7]:
df_women_5.head()

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,...,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT,TIME_FORMAT_LABEL,COMMENT_OBS,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,DZA,Algeria,GI_AII_82,"In law, women have the right to independent tr...",_T,...,Units,IX,Index,602,CCYY,NaN,A,Normal value,PU,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,DZA,Algeria,GI_AII_82,"In law, women have the right to independent tr...",_T,...,Units,IX,Index,602,CCYY,NaN,A,Normal value,PU,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,DZA,Algeria,GI_AII_82,"In law, women have the right to independent tr...",_T,...,Units,IX,Index,602,CCYY,NaN,A,Normal value,PU,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,DZA,Algeria,GI_AII_82,"In law, women have the right to independent tr...",_T,...,Units,IX,Index,602,CCYY,NaN,A,Normal value,PU,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,DZA,Algeria,GI_AII_82,"In law, women have the right to independent tr...",_T,...,Units,IX,Index,602,CCYY,NaN,A,Normal value,PU,Public

In [ ]:
df_women_1.shape

In [9]:
df_women_2.shape

(30753, 41)

In [10]:
df_women_3.shape

(1107, 38)

In [11]:
df_women_4.shape

(1314, 40)

In [12]:
df_women_5.shape

(594, 38)

In [ ]:
df_women_1.info()

In [14]:
df_women_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 30753 entries, 0 to 30752
Data columns (total 41 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   STRUCTURE               30753 non-null  str
 1   STRUCTURE_ID            30753 non-null  str
 2   ACTION                  30753 non-null  str
 3   FREQ                    30753 non-null  str
 4   REF_AREA                30753 non-null  str
 5   INDICATOR               30753 non-null  str
 6   SEX                     30753 non-null  str
 7   AGE                     30753 non-null  str
 8   URBANISATION            30753 non-null  str
 9   UNIT_MEASURE            30753 non-null  str
 10  COMP_BREAKDOWN_1        30753 non-null  str
 11  COMP_BREAKDOWN_2        30753 non-null  str
 12  COMP_BREAKDOWN_3        30753 non-null  str
 13  TIME_PERIOD             30753 non-null  int64
 14  OBS_VALUE               30753 non-null  str
 15  AGG_METHOD              30753 non-null  str
 16  UNIT_TYPE               30753 non-null  str
 17  DECIMALS                30753 non-null  int64
 18  DATABASE_ID             30753 non-null  str
 19  TIME_FORMAT             30753 non-null  int64
 20  UNIT_MULT               30753 non-null  int64
 21  OBS_STATUS              30753 non-null  str
 22  OBS_CONF                30753 non-null  str
 23  FREQ_LABEL              30753 non-null  str
 24  REF_AREA_LABEL          30753 non-null  str
 25  INDICATOR_LABEL         30753 non-null  str
 26  SEX_LABEL               30753 non-null  str
 27  AGE_LABEL               30753 non-null  str
 28  URBANISATION_LABEL      30753 non-null  str
 29  UNIT_MEASURE_LABEL      30753 non-null  str
 30  COMP_BREAKDOWN_1_LABEL  30753 non-null  str
 31  COMP_BREAKDOWN_2_LABEL  30753 non-null  str
 32  COMP_BREAKDOWN_3_LABEL  30753 non-null  str
 33  AGG_METHOD_LABEL        30753 non-null  str
 34  UNIT_TYPE_LABEL         30753 non-null  str
 35  DECIMALS_LABEL          30753 non-null  str
 36  DATABASE_ID_LABEL       30753 non-null  str
 37  TIME_FORMAT_LABEL       30753 non-null  str
 38  UNIT_MULT_LABEL         30753 non-null  str
 39  OBS_STATUS_LABEL        30753 non-null  str
 40  OBS_CONF_LABEL          30753 non-null  str
dtypes: int64(4), str(37)
memory usage: 9.6 MB

In [15]:
df_women_3.info()

<class 'pandas.DataFrame'>
RangeIndex: 1107 entries, 0 to 1106
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   STRUCTURE               1107 non-null   str
 1   STRUCTURE_ID            1107 non-null   str
 2   ACTION                  1107 non-null   str
 3   FREQ                    1107 non-null   str
 4   FREQ_LABEL              1107 non-null   str
 5   REF_AREA                1107 non-null   str
 6   REF_AREA_LABEL          1107 non-null   str
 7   INDICATOR               1107 non-null   str
 8   INDICATOR_LABEL         1107 non-null   str
 9   SEX                     1107 non-null   str
 10  SEX_LABEL               1107 non-null   str
 11  AGE                     1107 non-null   str
 12  AGE_LABEL               1107 non-null   str
 13  URBANISATION            1107 non-null   str
 14  URBANISATION_LABEL      1107 non-null   str
 15  UNIT_MEASURE            1107 non-null   str
 16  UNIT_MEASURE_LABEL      1107 non-null   str
 17  COMP_BREAKDOWN_1        1107 non-null   str
 18  COMP_BREAKDOWN_1_LABEL  1107 non-null   str
 19  COMP_BREAKDOWN_2        1107 non-null   str
 20  COMP_BREAKDOWN_2_LABEL  1107 non-null   str
 21  COMP_BREAKDOWN_3        1107 non-null   str
 22  COMP_BREAKDOWN_3_LABEL  1107 non-null   str
 23  TIME_PERIOD             1107 non-null   int64
 24  OBS_VALUE               1095 non-null   float64
 25  DATABASE_ID             1107 non-null   str
 26  DATABASE_ID_LABEL       1107 non-null   str
 27  UNIT_MULT               1107 non-null   int64
 28  UNIT_MULT_LABEL         1107 non-null   str
 29  UNIT_TYPE               1107 non-null   str
 30  UNIT_TYPE_LABEL         1107 non-null   str
 31  TIME_FORMAT             1107 non-null   int64
 32  TIME_FORMAT_LABEL       1107 non-null   str
 33  COMMENT_OBS             9 non-null      str
 34  OBS_STATUS              1107 non-null   str
 35  OBS_STATUS_LABEL        1107 non-null   str
 36  OBS_CONF                1107 non-null   str
 37  OBS_CONF_LABEL          1107 non-null   str
dtypes: float64(1), int64(3), str(34)
memory usage: 328.8 KB

In [16]:
df_women_4.info()

<class 'pandas.DataFrame'>
RangeIndex: 1314 entries, 0 to 1313
Data columns (total 40 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   STRUCTURE               1314 non-null   str
 1   STRUCTURE_ID            1314 non-null   str
 2   ACTION                  1314 non-null   str
 3   FREQ                    1314 non-null   str
 4   FREQ_LABEL              1314 non-null   str
 5   REF_AREA                1314 non-null   str
 6   REF_AREA_LABEL          1314 non-null   str
 7   INDICATOR               1314 non-null   str
 8   INDICATOR_LABEL         1314 non-null   str
 9   SEX                     1314 non-null   str
 10  SEX_LABEL               1314 non-null   str
 11  AGE                     1314 non-null   str
 12  AGE_LABEL               1314 non-null   str
 13  URBANISATION            1314 non-null   str
 14  URBANISATION_LABEL      1314 non-null   str
 15  UNIT_MEASURE            1314 non-null   str
 16  UNIT_MEASURE_LABEL      1314 non-null   str
 17  COMP_BREAKDOWN_1        1314 non-null   str
 18  COMP_BREAKDOWN_1_LABEL  1314 non-null   str
 19  COMP_BREAKDOWN_2        1314 non-null   str
 20  COMP_BREAKDOWN_2_LABEL  1314 non-null   str
 21  COMP_BREAKDOWN_3        1314 non-null   str
 22  COMP_BREAKDOWN_3_LABEL  1314 non-null   str
 23  TIME_PERIOD             1314 non-null   int64
 24  OBS_VALUE               1314 non-null   float64
 25  AGG_METHOD              1314 non-null   str
 26  AGG_METHOD_LABEL        1314 non-null   str
 27  DATABASE_ID             1314 non-null   str
 28  DATABASE_ID_LABEL       1314 non-null   str
 29  UNIT_MULT               1314 non-null   int64
 30  UNIT_MULT_LABEL         1314 non-null   str
 31  UNIT_TYPE               1314 non-null   str
 32  UNIT_TYPE_LABEL         1314 non-null   str
 33  TIME_FORMAT             1314 non-null   int64
 34  TIME_FORMAT_LABEL       1314 non-null   str
 35  COMMENT_OBS             0 non-null      float64
 36  OBS_STATUS              1314 non-null   str
 37  OBS_STATUS_LABEL        1314 non-null   str
 38  OBS_CONF                1314 non-null   str
 39  OBS_CONF_LABEL          1314 non-null   str
dtypes: float64(2), int64(3), str(35)
memory usage: 410.8 KB

In [17]:
df_women_5.info()

<class 'pandas.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   STRUCTURE               594 non-null    str
 1   STRUCTURE_ID            594 non-null    str
 2   ACTION                  594 non-null    str
 3   FREQ                    594 non-null    str
 4   FREQ_LABEL              594 non-null    str
 5   REF_AREA                594 non-null    str
 6   REF_AREA_LABEL          594 non-null    str
 7   INDICATOR               594 non-null    str
 8   INDICATOR_LABEL         594 non-null    str
 9   SEX                     594 non-null    str
 10  SEX_LABEL               594 non-null    str
 11  AGE                     594 non-null    str
 12  AGE_LABEL               594 non-null    str
 13  URBANISATION            594 non-null    str
 14  URBANISATION_LABEL      594 non-null    str
 15  UNIT_MEASURE            594 non-null    str
 16  UNIT_MEASURE_LABEL      594 non-null    str
 17  COMP_BREAKDOWN_1        594 non-null    str
 18  COMP_BREAKDOWN_1_LABEL  594 non-null    str
 19  COMP_BREAKDOWN_2        594 non-null    str
 20  COMP_BREAKDOWN_2_LABEL  594 non-null    str
 21  COMP_BREAKDOWN_3        594 non-null    str
 22  COMP_BREAKDOWN_3_LABEL  594 non-null    str
 23  TIME_PERIOD             594 non-null    int64
 24  OBS_VALUE               270 non-null    float64
 25  DATABASE_ID             594 non-null    str
 26  DATABASE_ID_LABEL       594 non-null    str
 27  UNIT_MULT               594 non-null    int64
 28  UNIT_MULT_LABEL         594 non-null    str
 29  UNIT_TYPE               594 non-null    str
 30  UNIT_TYPE_LABEL         594 non-null    str
 31  TIME_FORMAT             594 non-null    int64
 32  TIME_FORMAT_LABEL       594 non-null    str
 33  COMMENT_OBS             0 non-null      float64
 34  OBS_STATUS              594 non-null    str
 35  OBS_STATUS_LABEL        594 non-null    str
 36  OBS_CONF                594 non-null    str
 37  OBS_CONF_LABEL          594 non-null    str
dtypes: float64(2), int64(3), str(33)
memory usage: 176.5 KB

Propuesta 1: ¿Qué hace feliz a Europa?
Idea general
Título posible:
“¿Qué hace feliz a Europa? Un análisis de felicidad, economía y cohesión social”
Tema:
Analizar por qué unos países europeos son más “felices” que otros, usando el World Happiness Report y variables socioeconómicas (PIB per cápita, esperanza de vida, apoyo social, etc.). Puedes centrarte en Europa y comparar regiones (Norte vs Sur, Este vs Oeste) y situar a España dentro del mapa.
El World Happiness Report tiene datasets muy usados en proyectos de Data Science, con columnas como “Happiness Score”, “GDP per capita”, “Social support”, “Healthy life expectancy”, etc.
Además, puedes cruzarlo con datos abiertos europeos (Eurostat / data.europa.eu) para añadir variables extra (por ejemplo, desempleo juvenil, gasto social, etc.).
Hipótesis posibles
- Hipótesis 1 (principal):
“Los países europeos con mayor PIB per cápita y esperanza de vida presentan niveles de felicidad significativamente más altos.”
- Hipótesis 2:
“El apoyo social (social support) explica mejor la felicidad que el PIB per cápita.”
- Hipótesis 3 (toque simpático):
“Los países con clima más suave (menos extremos de temperatura) no son necesariamente los más felices.”
- Hipótesis 4:
“España se sitúa por encima de la media europea en felicidad, pero por debajo en percepción de corrupción.”
Puedes jugar con mapas, heatmaps de correlación, comparaciones por regiones, etc., encajando muy bien con la guía de EDA que te han dado (univariante, bivariante, multivariante).